# Generated by Django 5.0.4 on 2024-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
